/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EsetEnterpriseInspector);
  }
}(this, function(expect, EsetEnterpriseInspector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExclusionDetailsResponseEXCLUSION', function() {
    it('should create an instance of ExclusionDetailsResponseEXCLUSION', function() {
      // uncomment below and update the code to test ExclusionDetailsResponseEXCLUSION
      //var instane = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be.a(EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION);
    });

    it('should have the property body (base name: "body")', function() {
      // uncomment below and update the code to test the property body
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property ruleIds (base name: "ruleIds")', function() {
      // uncomment below and update the code to test the property ruleIds
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property ruleUuids (base name: "ruleUuids")', function() {
      // uncomment below and update the code to test the property ruleUuids
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new EsetEnterpriseInspector.ExclusionDetailsResponseEXCLUSION();
      //expect(instance).to.be();
    });

  });

}));
