/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EsetEnterpriseInspector);
  }
}(this, function(expect, EsetEnterpriseInspector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RuleCreateRequestDescription', function() {
    it('should create an instance of RuleCreateRequestDescription', function() {
      // uncomment below and update the code to test RuleCreateRequestDescription
      //var instane = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be.a(EsetEnterpriseInspector.RuleCreateRequestDescription);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property explanation (base name: "explanation")', function() {
      // uncomment below and update the code to test the property explanation
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property os (base name: "os")', function() {
      // uncomment below and update the code to test the property os
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property mitreattackid (base name: "mitreattackid")', function() {
      // uncomment below and update the code to test the property mitreattackid
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property maliciousCauses (base name: "maliciousCauses")', function() {
      // uncomment below and update the code to test the property maliciousCauses
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property benignCauses (base name: "benignCauses")', function() {
      // uncomment below and update the code to test the property benignCauses
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

    it('should have the property recommendedActions (base name: "recommendedActions")', function() {
      // uncomment below and update the code to test the property recommendedActions
      //var instance = new EsetEnterpriseInspector.RuleCreateRequestDescription();
      //expect(instance).to.be();
    });

  });

}));
