#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DetectionListResponseValue' {
    Context 'DetectionListResponseValue' {
        It 'Initialize-DetectionListResponseValue' {
            # a simple test to create an object
            #$NewObject = Initialize-DetectionListResponseValue -ComputerId "TEST_VALUE" -ComputerName "TEST_VALUE" -ComputerUuid "TEST_VALUE" -CreationTime "TEST_VALUE" -Id "TEST_VALUE" -ModuleId "TEST_VALUE" -ModuleLgAge "TEST_VALUE" -ModuleLgPopularity "TEST_VALUE" -ModuleLgReputation "TEST_VALUE" -ModuleName "TEST_VALUE" -ModuleSha1 "TEST_VALUE" -ModuleSignatureType "TEST_VALUE" -ModuleSigner "TEST_VALUE" -Note "TEST_VALUE" -Priority "TEST_VALUE" -ProcessCommandLine "TEST_VALUE" -ProcessId "TEST_VALUE" -ProcessUser "TEST_VALUE" -Resolved "TEST_VALUE" -RuleId "TEST_VALUE" -RuleName "TEST_VALUE" -RuleUuid "TEST_VALUE" -Severity "TEST_VALUE" -SeverityScore "TEST_VALUE" -ThreatName "TEST_VALUE" -ThreatUri "TEST_VALUE" -Type "TEST_VALUE" -Uuid "TEST_VALUE"
            #$NewObject | Should -BeOfType DetectionListResponseValue
            #$NewObject.property | Should -Be 0
        }
    }
}
