#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DetectionUpdateRequest' {
    Context 'DetectionUpdateRequest' {
        It 'Initialize-DetectionUpdateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-DetectionUpdateRequest -Resolved "TEST_VALUE" -Priority "TEST_VALUE" -Note "TEST_VALUE"
            #$NewObject | Should -BeOfType DetectionUpdateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
