#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DetectionListResponse' {
    Context 'DetectionListResponse' {
        It 'Initialize-DetectionListResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-DetectionListResponse -Count "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType DetectionListResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
