#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionListResponseValue' {
    Context 'ExclusionListResponseValue' {
        It 'Initialize-ExclusionListResponseValue' {
            # a simple test to create an object
            #$NewObject = Initialize-ExclusionListResponseValue -Enabled "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Note "TEST_VALUE" -Uuid "TEST_VALUE"
            #$NewObject | Should -BeOfType ExclusionListResponseValue
            #$NewObject.property | Should -Be 0
        }
    }
}
