#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionDetailsResponseEXCLUSION' {
    Context 'ExclusionDetailsResponseEXCLUSION' {
        It 'Initialize-ExclusionDetailsResponseEXCLUSION' {
            # a simple test to create an object
            #$NewObject = Initialize-ExclusionDetailsResponseEXCLUSION -Body "TEST_VALUE" -Enabled "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Note "TEST_VALUE" -RuleIds "TEST_VALUE" -RuleUuids "TEST_VALUE" -Uuid "TEST_VALUE"
            #$NewObject | Should -BeOfType ExclusionDetailsResponseEXCLUSION
            #$NewObject.property | Should -Be 0
        }
    }
}
