#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionListResponse' {
    Context 'ExclusionListResponse' {
        It 'Initialize-ExclusionListResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-ExclusionListResponse -Count "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType ExclusionListResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
