#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionCreateRequest' {
    Context 'ExclusionCreateRequest' {
        It 'Initialize-ExclusionCreateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-ExclusionCreateRequest -Body "TEST_VALUE" -AutoResolve "TEST_VALUE" -Name "TEST_VALUE" -RuleIds "TEST_VALUE" -RuleUuids "TEST_VALUE" -Note "TEST_VALUE"
            #$NewObject | Should -BeOfType ExclusionCreateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
