#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionDetailsResponse' {
    Context 'ExclusionDetailsResponse' {
        It 'Initialize-ExclusionDetailsResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-ExclusionDetailsResponse -EXCLUSION "TEST_VALUE"
            #$NewObject | Should -BeOfType ExclusionDetailsResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
