#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExecutableUnblockRequest' {
    Context 'ExecutableUnblockRequest' {
        It 'Initialize-ExecutableUnblockRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-ExecutableUnblockRequest -Note "TEST_VALUE"
            #$NewObject | Should -BeOfType ExecutableUnblockRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
