#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'IsolateResponse' {
    Context 'IsolateResponse' {
        It 'Initialize-IsolateResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-IsolateResponse -TaskUuid "TEST_VALUE"
            #$NewObject | Should -BeOfType IsolateResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
