#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestActions' {
    Context 'RuleCreateRequestActions' {
        It 'Initialize-RuleCreateRequestActions' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestActions -Action "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestActions
            #$NewObject.property | Should -Be 0
        }
    }
}
