#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestActionsAction' {
    Context 'RuleCreateRequestActionsAction' {
        It 'Initialize-RuleCreateRequestActionsAction' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestActionsAction -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestActionsAction
            #$NewObject.property | Should -Be 0
        }
    }
}
