#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateResponse' {
    Context 'RuleCreateResponse' {
        It 'Initialize-RuleCreateResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateResponse -Body "TEST_VALUE" -Enabled "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Severity "TEST_VALUE" -SeverityScore "TEST_VALUE" -Uuid "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
