#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestDescription' {
    Context 'RuleCreateRequestDescription' {
        It 'Initialize-RuleCreateRequestDescription' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestDescription -Name "TEST_VALUE" -Category "TEST_VALUE" -Explanation "TEST_VALUE" -Os "TEST_VALUE" -Mitreattackid "TEST_VALUE" -MaliciousCauses "TEST_VALUE" -BenignCauses "TEST_VALUE" -RecommendedActions "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestDescription
            #$NewObject.property | Should -Be 0
        }
    }
}
