#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestDefinitionOperations' {
    Context 'RuleCreateRequestDefinitionOperations' {
        It 'Initialize-RuleCreateRequestDefinitionOperations' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestDefinitionOperations -Operation "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestDefinitionOperations
            #$NewObject.property | Should -Be 0
        }
    }
}
