#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleUpdateRequest' {
    Context 'RuleUpdateRequest' {
        It 'Initialize-RuleUpdateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleUpdateRequest -Enabled "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleUpdateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
