#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequest' {
    Context 'RuleCreateRequest' {
        It 'Initialize-RuleCreateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequest -Definition "TEST_VALUE" -Description "TEST_VALUE" -Actions "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
