#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestDefinition' {
    Context 'RuleCreateRequestDefinition' {
        It 'Initialize-RuleCreateRequestDefinition' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestDefinition -Ancestor "TEST_VALUE" -Parentprocess "TEST_VALUE" -VarProcess "TEST_VALUE" -Operations "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestDefinition
            #$NewObject.property | Should -Be 0
        }
    }
}
