#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleListResponse' {
    Context 'RuleListResponse' {
        It 'Initialize-RuleListResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleListResponse -Count "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleListResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
