#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RuleCreateRequestDefinitionOperationsOperation' {
    Context 'RuleCreateRequestDefinitionOperationsOperation' {
        It 'Initialize-RuleCreateRequestDefinitionOperationsOperation' {
            # a simple test to create an object
            #$NewObject = Initialize-RuleCreateRequestDefinitionOperationsOperation -Type "TEST_VALUE"
            #$NewObject | Should -BeOfType RuleCreateRequestDefinitionOperationsOperation
            #$NewObject.property | Should -Be 0
        }
    }
}
