#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'UnauthorizedError' {
    Context 'UnauthorizedError' {
        It 'Initialize-UnauthorizedError' {
            # a simple test to create an object
            #$NewObject = Initialize-UnauthorizedError -VarError "TEST_VALUE"
            #$NewObject | Should -BeOfType UnauthorizedError
            #$NewObject.property | Should -Be 0
        }
    }
}
