/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthenticateRequest from '../model/AuthenticateRequest';
import UnauthorizedError from '../model/UnauthorizedError';

/**
* Authentication service.
* @module api/AuthenticationApi
* @version 1.6-oas3
*/
export default class AuthenticationApi {

    /**
    * Constructs a new AuthenticationApi. 
    * @alias module:api/AuthenticationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the authenticatePost operation.
     * @callback module:api/AuthenticationApi~authenticatePostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Authentication
     * Authenticate
     * @param {module:model/AuthenticateRequest} authenticateRequest 
     * @param {module:api/AuthenticationApi~authenticatePostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authenticatePost(authenticateRequest, callback) {
      let postBody = authenticateRequest;
      // verify the required parameter 'authenticateRequest' is set
      if (authenticateRequest === undefined || authenticateRequest === null) {
        throw new Error("Missing the required parameter 'authenticateRequest' when calling authenticatePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/authenticate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the authenticatePut operation.
     * @callback module:api/AuthenticationApi~authenticatePutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Authentication
     * Authenticate
     * @param {module:model/AuthenticateRequest} authenticateRequest 
     * @param {module:api/AuthenticationApi~authenticatePutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    authenticatePut(authenticateRequest, callback) {
      let postBody = authenticateRequest;
      // verify the required parameter 'authenticateRequest' is set
      if (authenticateRequest === undefined || authenticateRequest === null) {
        throw new Error("Missing the required parameter 'authenticateRequest' when calling authenticatePut");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/authenticate', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
