/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DetectionDetailsResponse from '../model/DetectionDetailsResponse';
import DetectionListResponse from '../model/DetectionListResponse';
import DetectionUpdateRequest from '../model/DetectionUpdateRequest';
import UnauthorizedError from '../model/UnauthorizedError';

/**
* Detections service.
* @module api/DetectionsApi
* @version 1.6-oas3
*/
export default class DetectionsApi {

    /**
    * Constructs a new DetectionsApi. 
    * @alias module:api/DetectionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getDetectionDetails operation.
     * @callback module:api/DetectionsApi~getDetectionDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DetectionDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get detection details
     * @param {String} id ID or UUID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/DetectionsApi~getDetectionDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DetectionDetailsResponse}
     */
    getDetectionDetails(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getDetectionDetails");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DetectionDetailsResponse;
      return this.apiClient.callApi(
        '/api/v1/detections/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listDetections operation.
     * @callback module:api/DetectionsApi~listDetectionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DetectionListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List of detections
     * @param {Object} opts Optional parameters
     * @param {Number} opts.top system query option requests the number of items in the queried collection to be included in the result
     * @param {Number} opts.skip system query option requests the number of items in the queried collection that are to be skipped and not included in the result
     * @param {module:model/Number} opts.count system query option allows clients to request a count of the matching resources included with the resources in the response. if set to $count=1, the number of detections is returned.
     * @param {String} opts.orderBy system query option allows clients to request resources in either ascending order using asc or descending order using desc. If not specified the order is in ascending way
     * @param {String} opts.filter system query option allows clients to filter a collection of resources that are addressed by a request URL. The query supports the following operators eq, ne, gt, ge, lt, le, and, or, and (). Operators can be combined with values to filter data. For instance, “resolved eq 0” will report only unresolved detections.
     * @param {module:api/DetectionsApi~listDetectionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DetectionListResponse}
     */
    listDetections(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        '$top': opts['top'],
        '$skip': opts['skip'],
        '$count': opts['count'],
        '$orderBy': opts['orderBy'],
        '$filter': opts['filter']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DetectionListResponse;
      return this.apiClient.callApi(
        '/api/v1/detections', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDetection operation.
     * @callback module:api/DetectionsApi~updateDetectionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update detection
     * @param {String} id ID or UUID
     * @param {module:model/DetectionUpdateRequest} detectionUpdateRequest 
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/DetectionsApi~updateDetectionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateDetection(id, detectionUpdateRequest, opts, callback) {
      opts = opts || {};
      let postBody = detectionUpdateRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateDetection");
      }
      // verify the required parameter 'detectionUpdateRequest' is set
      if (detectionUpdateRequest === undefined || detectionUpdateRequest === null) {
        throw new Error("Missing the required parameter 'detectionUpdateRequest' when calling updateDetection");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/detections/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
