/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ExclusionCreateRequest from '../model/ExclusionCreateRequest';
import ExclusionDetailsResponse from '../model/ExclusionDetailsResponse';
import ExclusionListResponse from '../model/ExclusionListResponse';
import UnauthorizedError from '../model/UnauthorizedError';

/**
* Exclusions service.
* @module api/ExclusionsApi
* @version 1.6-oas3
*/
export default class ExclusionsApi {

    /**
    * Constructs a new ExclusionsApi. 
    * @alias module:api/ExclusionsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createExclusion operation.
     * @callback module:api/ExclusionsApi~createExclusionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExclusionDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a new exclusion
     * @param {module:model/ExclusionCreateRequest} exclusionCreateRequest 
     * @param {module:api/ExclusionsApi~createExclusionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExclusionDetailsResponse}
     */
    createExclusion(exclusionCreateRequest, callback) {
      let postBody = exclusionCreateRequest;
      // verify the required parameter 'exclusionCreateRequest' is set
      if (exclusionCreateRequest === undefined || exclusionCreateRequest === null) {
        throw new Error("Missing the required parameter 'exclusionCreateRequest' when calling createExclusion");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ExclusionDetailsResponse;
      return this.apiClient.callApi(
        '/api/v1/exclusions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteExclusion operation.
     * @callback module:api/ExclusionsApi~deleteExclusionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes an exclusion
     * @param {String} exclusionId Exclusion ID or UUID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/ExclusionsApi~deleteExclusionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteExclusion(exclusionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'exclusionId' is set
      if (exclusionId === undefined || exclusionId === null) {
        throw new Error("Missing the required parameter 'exclusionId' when calling deleteExclusion");
      }

      let pathParams = {
        'exclusionId': exclusionId
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/exclusions/{exclusionId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the editExclusion operation.
     * @callback module:api/ExclusionsApi~editExclusionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExclusionDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edits exclusion body
     * @param {String} exclusionId Exclusion ID or UUID
     * @param {module:model/ExclusionCreateRequest} exclusionCreateRequest 
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/ExclusionsApi~editExclusionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExclusionDetailsResponse}
     */
    editExclusion(exclusionId, exclusionCreateRequest, opts, callback) {
      opts = opts || {};
      let postBody = exclusionCreateRequest;
      // verify the required parameter 'exclusionId' is set
      if (exclusionId === undefined || exclusionId === null) {
        throw new Error("Missing the required parameter 'exclusionId' when calling editExclusion");
      }
      // verify the required parameter 'exclusionCreateRequest' is set
      if (exclusionCreateRequest === undefined || exclusionCreateRequest === null) {
        throw new Error("Missing the required parameter 'exclusionCreateRequest' when calling editExclusion");
      }

      let pathParams = {
        'exclusionId': exclusionId
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ExclusionDetailsResponse;
      return this.apiClient.callApi(
        '/api/v1/exclusions/{exclusionId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getExclusionDetails operation.
     * @callback module:api/ExclusionsApi~getExclusionDetailsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExclusionDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Gets a single exclusion
     * @param {String} exclusionId Exclusion ID or UUID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/ExclusionsApi~getExclusionDetailsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExclusionDetailsResponse}
     */
    getExclusionDetails(exclusionId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'exclusionId' is set
      if (exclusionId === undefined || exclusionId === null) {
        throw new Error("Missing the required parameter 'exclusionId' when calling getExclusionDetails");
      }

      let pathParams = {
        'exclusionId': exclusionId
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExclusionDetailsResponse;
      return this.apiClient.callApi(
        '/api/v1/exclusions/{exclusionId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getExclusionsByRule operation.
     * @callback module:api/ExclusionsApi~getExclusionsByRuleCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Number>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get exclusions associated with a rule
     * @param {String} ruleId Rule ID or UUID
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.idType if $idType=uuid {id} in URL is interpreted as uuid
     * @param {module:api/ExclusionsApi~getExclusionsByRuleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Number>}
     */
    getExclusionsByRule(ruleId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ruleId' is set
      if (ruleId === undefined || ruleId === null) {
        throw new Error("Missing the required parameter 'ruleId' when calling getExclusionsByRule");
      }

      let pathParams = {
        'ruleId': ruleId
      };
      let queryParams = {
        '$idType': opts['idType']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['Number'];
      return this.apiClient.callApi(
        '/api/v1/exclusions/rule/{ruleId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listExclusions operation.
     * @callback module:api/ExclusionsApi~listExclusionsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExclusionListResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List exclusions
     * @param {Object} opts Optional parameters
     * @param {Number} opts.top system query option requests the number of items in the queried collection to be included in the result
     * @param {Number} opts.skip system query option requests the number of items in the queried collection that are to be skipped and not included in the result
     * @param {module:model/Number} opts.count system query option allows clients to request a count of the matching resources included with the resources in the response. if set to $count=1, the number of detections is returned.
     * @param {String} opts.orderBy system query option allows clients to request resources in either ascending order using asc or descending order using desc. If not specified the order is in ascending way
     * @param {String} opts.filter system query option allows clients to filter a collection of resources that are addressed by a request URL. The query supports the following operators eq, ne, gt, ge, lt, le, and, or, and (). Operators can be combined with values to filter data. For instance, “resolved eq 0” will report only unresolved detections.
     * @param {module:api/ExclusionsApi~listExclusionsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExclusionListResponse}
     */
    listExclusions(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        '$top': opts['top'],
        '$skip': opts['skip'],
        '$count': opts['count'],
        '$orderBy': opts['orderBy'],
        '$filter': opts['filter']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ExclusionListResponse;
      return this.apiClient.callApi(
        '/api/v1/exclusions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
