/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EsetEnterpriseInspector);
  }
}(this, function(expect, EsetEnterpriseInspector) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EsetEnterpriseInspector.ExclusionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExclusionsApi', function() {
    describe('createExclusion', function() {
      it('should call createExclusion successfully', function(done) {
        //uncomment below and update the code to test createExclusion
        //instance.createExclusion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteExclusion', function() {
      it('should call deleteExclusion successfully', function(done) {
        //uncomment below and update the code to test deleteExclusion
        //instance.deleteExclusion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('editExclusion', function() {
      it('should call editExclusion successfully', function(done) {
        //uncomment below and update the code to test editExclusion
        //instance.editExclusion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getExclusionDetails', function() {
      it('should call getExclusionDetails successfully', function(done) {
        //uncomment below and update the code to test getExclusionDetails
        //instance.getExclusionDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getExclusionsByRule', function() {
      it('should call getExclusionsByRule successfully', function(done) {
        //uncomment below and update the code to test getExclusionsByRule
        //instance.getExclusionsByRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listExclusions', function() {
      it('should call listExclusions successfully', function(done) {
        //uncomment below and update the code to test listExclusions
        //instance.listExclusions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
