#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AuthenticationApi' {
    Context 'Invoke-AuthenticatePost' {
        It 'Test Invoke-AuthenticatePost' {
            #$TestResult = Invoke-AuthenticatePost -AuthenticateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-AuthenticatePut' {
        It 'Test Invoke-AuthenticatePut' {
            #$TestResult = Invoke-AuthenticatePut -AuthenticateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
