#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ComputersApi' {
    Context 'ConvertTo-tegrateComputer' {
        It 'Test ConvertTo-tegrateComputer' {
            #$TestResult = ConvertTo-tegrateComputer -ComputerId "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-IsolateComputer' {
        It 'Test Invoke-IsolateComputer' {
            #$TestResult = Invoke-IsolateComputer -ComputerId "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
