#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'DetectionsApi' {
    Context 'Get-DetectionDetails' {
        It 'Test Get-DetectionDetails' {
            #$TestResult = Get-DetectionDetails -Id "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ListDetections' {
        It 'Test Invoke-ListDetections' {
            #$TestResult = Invoke-ListDetections -Top "TEST_VALUE" -Skip "TEST_VALUE" -Count "TEST_VALUE" -OrderBy "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-Detection' {
        It 'Test Update-Detection' {
            #$TestResult = Update-Detection -Id "TEST_VALUE" -DetectionUpdateRequest "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
