#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ExclusionsApi' {
    Context 'New-Exclusion' {
        It 'Test New-Exclusion' {
            #$TestResult = New-Exclusion -ExclusionCreateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteExclusion' {
        It 'Test Invoke-DeleteExclusion' {
            #$TestResult = Invoke-DeleteExclusion -ExclusionId "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Edit-Exclusion' {
        It 'Test Edit-Exclusion' {
            #$TestResult = Edit-Exclusion -ExclusionId "TEST_VALUE" -ExclusionCreateRequest "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ExclusionDetails' {
        It 'Test Get-ExclusionDetails' {
            #$TestResult = Get-ExclusionDetails -ExclusionId "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-ExclusionsByRule' {
        It 'Test Get-ExclusionsByRule' {
            #$TestResult = Get-ExclusionsByRule -RuleId "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ListExclusions' {
        It 'Test Invoke-ListExclusions' {
            #$TestResult = Invoke-ListExclusions -Top "TEST_VALUE" -Skip "TEST_VALUE" -Count "TEST_VALUE" -OrderBy "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
