#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RemediationApi' {
    Context 'Block-Executable' {
        It 'Test Block-Executable' {
            #$TestResult = Block-Executable -Id "TEST_VALUE" -IdType "TEST_VALUE" -ExecutableBlockRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Unblock-Executable' {
        It 'Test Unblock-Executable' {
            #$TestResult = Unblock-Executable -Id "TEST_VALUE" -IdType "TEST_VALUE" -ExecutableUnblockRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
