#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'RulesApi' {
    Context 'New-Rule' {
        It 'Test New-Rule' {
            #$TestResult = New-Rule -RuleCreateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-DeleteRule' {
        It 'Test Invoke-DeleteRule' {
            #$TestResult = Invoke-DeleteRule -Id "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Edit-Rule' {
        It 'Test Edit-Rule' {
            #$TestResult = Edit-Rule -Id "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-RuleDetails' {
        It 'Test Get-RuleDetails' {
            #$TestResult = Get-RuleDetails -Id "TEST_VALUE" -IdType "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ListRules' {
        It 'Test Invoke-ListRules' {
            #$TestResult = Invoke-ListRules -Top "TEST_VALUE" -Skip "TEST_VALUE" -Count "TEST_VALUE" -OrderBy "TEST_VALUE" -Filter "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-Rule' {
        It 'Test Update-Rule' {
            #$TestResult = Update-Rule -Id "TEST_VALUE" -IdType "TEST_VALUE" -RuleUpdateRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
