#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DETECTION
No description available.
.OUTPUTS

DetectionDetailsResponse<PSCustomObject>
#>

function Initialize-DetectionDetailsResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DETECTION}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => DetectionDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "DETECTION" = ${DETECTION}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DetectionDetailsResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to DetectionDetailsResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DetectionDetailsResponse<PSCustomObject>
#>
function ConvertFrom-JsonToDetectionDetailsResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => DetectionDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DetectionDetailsResponse
        $AllProperties = ("DETECTION")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DETECTION"))) { #optional property not found
            $DETECTION = $null
        } else {
            $DETECTION = $JsonParameters.PSobject.Properties["DETECTION"].value
        }

        $PSO = [PSCustomObject]@{
            "DETECTION" = ${DETECTION}
        }

        return $PSO
    }

}

