#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER EXCLUSION
No description available.
.OUTPUTS

ExclusionDetailsResponse<PSCustomObject>
#>

function Initialize-ExclusionDetailsResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${EXCLUSION}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ExclusionDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "EXCLUSION" = ${EXCLUSION}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ExclusionDetailsResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to ExclusionDetailsResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ExclusionDetailsResponse<PSCustomObject>
#>
function ConvertFrom-JsonToExclusionDetailsResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ExclusionDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ExclusionDetailsResponse
        $AllProperties = ("EXCLUSION")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EXCLUSION"))) { #optional property not found
            $EXCLUSION = $null
        } else {
            $EXCLUSION = $JsonParameters.PSobject.Properties["EXCLUSION"].value
        }

        $PSO = [PSCustomObject]@{
            "EXCLUSION" = ${EXCLUSION}
        }

        return $PSO
    }

}

