#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Distance
No description available.
.PARAMETER Unique
No description available.
.OUTPUTS

RuleCreateRequestDefinitionAncestor<PSCustomObject>
#>

function Initialize-RuleCreateRequestDefinitionAncestor {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Distance},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Unique}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RuleCreateRequestDefinitionAncestor' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($Distance -and $Distance -lt 1) {
          throw "invalid value for 'Distance', must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "distance" = ${Distance}
            "unique" = ${Unique}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RuleCreateRequestDefinitionAncestor<PSCustomObject>

.DESCRIPTION

Convert from JSON to RuleCreateRequestDefinitionAncestor<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RuleCreateRequestDefinitionAncestor<PSCustomObject>
#>
function ConvertFrom-JsonToRuleCreateRequestDefinitionAncestor {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RuleCreateRequestDefinitionAncestor' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RuleCreateRequestDefinitionAncestor
        $AllProperties = ("distance", "unique")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "distance"))) { #optional property not found
            $Distance = $null
        } else {
            $Distance = $JsonParameters.PSobject.Properties["distance"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "unique"))) { #optional property not found
            $Unique = $null
        } else {
            $Unique = $JsonParameters.PSobject.Properties["unique"].value
        }

        $PSO = [PSCustomObject]@{
            "distance" = ${Distance}
            "unique" = ${Unique}
        }

        return $PSO
    }

}

