#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER RULE
No description available.
.OUTPUTS

RuleDetailsResponse<PSCustomObject>
#>

function Initialize-RuleDetailsResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RULE}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RuleDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "RULE" = ${RULE}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RuleDetailsResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to RuleDetailsResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RuleDetailsResponse<PSCustomObject>
#>
function ConvertFrom-JsonToRuleDetailsResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RuleDetailsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RuleDetailsResponse
        $AllProperties = ("RULE")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "RULE"))) { #optional property not found
            $RULE = $null
        } else {
            $RULE = $JsonParameters.PSobject.Properties["RULE"].value
        }

        $PSO = [PSCustomObject]@{
            "RULE" = ${RULE}
        }

        return $PSO
    }

}

