#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Operation
No description available.
.OUTPUTS

RuleCreateRequestDefinitionOperations<PSCustomObject>
#>

function Initialize-RuleCreateRequestDefinitionOperations {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Operation}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RuleCreateRequestDefinitionOperations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "operation" = ${Operation}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RuleCreateRequestDefinitionOperations<PSCustomObject>

.DESCRIPTION

Convert from JSON to RuleCreateRequestDefinitionOperations<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RuleCreateRequestDefinitionOperations<PSCustomObject>
#>
function ConvertFrom-JsonToRuleCreateRequestDefinitionOperations {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RuleCreateRequestDefinitionOperations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RuleCreateRequestDefinitionOperations
        $AllProperties = ("operation")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "operation"))) { #optional property not found
            $Operation = $null
        } else {
            $Operation = $JsonParameters.PSobject.Properties["operation"].value
        }

        $PSO = [PSCustomObject]@{
            "operation" = ${Operation}
        }

        return $PSO
    }

}

