#
# ESET Enterprise Inspector
# ESET Enterprise Inspector REST API definition
# Version: 1.6-oas3
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Enabled
No description available.
.PARAMETER Id
No description available.
.PARAMETER Name
No description available.
.PARAMETER Severity
No description available.
.PARAMETER SeverityScore
No description available.
.OUTPUTS

RuleListResponseValue<PSCustomObject>
#>

function Initialize-RuleListResponseValue {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("1", "2", "3")]
        [System.Nullable[Int32]]
        ${Severity},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${SeverityScore}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RuleListResponseValue' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($SeverityScore -and $SeverityScore -gt 100) {
          throw "invalid value for 'SeverityScore', must be smaller than or equal to 100."
        }


        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "id" = ${Id}
            "name" = ${Name}
            "severity" = ${Severity}
            "severityScore" = ${SeverityScore}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RuleListResponseValue<PSCustomObject>

.DESCRIPTION

Convert from JSON to RuleListResponseValue<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RuleListResponseValue<PSCustomObject>
#>
function ConvertFrom-JsonToRuleListResponseValue {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RuleListResponseValue' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RuleListResponseValue
        $AllProperties = ("enabled", "id", "name", "severity", "severityScore")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "severity"))) { #optional property not found
            $Severity = $null
        } else {
            $Severity = $JsonParameters.PSobject.Properties["severity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "severityScore"))) { #optional property not found
            $SeverityScore = $null
        } else {
            $SeverityScore = $JsonParameters.PSobject.Properties["severityScore"].value
        }

        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "id" = ${Id}
            "name" = ${Name}
            "severity" = ${Severity}
            "severityScore" = ${SeverityScore}
        }

        return $PSO
    }

}

