/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthenticateRequest model module.
 * @module model/AuthenticateRequest
 * @version 1.6-oas3
 */
class AuthenticateRequest {
    /**
     * Constructs a new <code>AuthenticateRequest</code>.
     * Credentials to use for authentication. Set domain to \&quot;true\&quot; if this a domain user.
     * @alias module:model/AuthenticateRequest
     * @param username {String} 
     * @param password {String} 
     * @param domain {Boolean} 
     */
    constructor(username, password, domain) { 
        
        AuthenticateRequest.initialize(this, username, password, domain);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, domain) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['domain'] = domain;
    }

    /**
     * Constructs a <code>AuthenticateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthenticateRequest} obj Optional instance to populate.
     * @return {module:model/AuthenticateRequest} The populated <code>AuthenticateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthenticateRequest();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('domain')) {
                obj['domain'] = ApiClient.convertToType(data['domain'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
AuthenticateRequest.prototype['username'] = undefined;

/**
 * @member {String} password
 */
AuthenticateRequest.prototype['password'] = undefined;

/**
 * @member {Boolean} domain
 */
AuthenticateRequest.prototype['domain'] = undefined;






export default AuthenticateRequest;

