/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DetectionUpdateRequest model module.
 * @module model/DetectionUpdateRequest
 * @version 1.6-oas3
 */
class DetectionUpdateRequest {
    /**
     * Constructs a new <code>DetectionUpdateRequest</code>.
     * @alias module:model/DetectionUpdateRequest
     */
    constructor() { 
        
        DetectionUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DetectionUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetectionUpdateRequest} obj Optional instance to populate.
     * @return {module:model/DetectionUpdateRequest} The populated <code>DetectionUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetectionUpdateRequest();

            if (data.hasOwnProperty('resolved')) {
                obj['resolved'] = ApiClient.convertToType(data['resolved'], 'Boolean');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} resolved
 */
DetectionUpdateRequest.prototype['resolved'] = undefined;

/**
 * @member {Number} priority
 */
DetectionUpdateRequest.prototype['priority'] = undefined;

/**
 * @member {String} note
 */
DetectionUpdateRequest.prototype['note'] = undefined;






export default DetectionUpdateRequest;

