/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DetectionDetailsResponseDETECTION model module.
 * @module model/DetectionDetailsResponseDETECTION
 * @version 1.6-oas3
 */
class DetectionDetailsResponseDETECTION {
    /**
     * Constructs a new <code>DetectionDetailsResponseDETECTION</code>.
     * @alias module:model/DetectionDetailsResponseDETECTION
     */
    constructor() { 
        
        DetectionDetailsResponseDETECTION.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DetectionDetailsResponseDETECTION</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetectionDetailsResponseDETECTION} obj Optional instance to populate.
     * @return {module:model/DetectionDetailsResponseDETECTION} The populated <code>DetectionDetailsResponseDETECTION</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetectionDetailsResponseDETECTION();

            if (data.hasOwnProperty('computerId')) {
                obj['computerId'] = ApiClient.convertToType(data['computerId'], 'Number');
            }
            if (data.hasOwnProperty('computerName')) {
                obj['computerName'] = ApiClient.convertToType(data['computerName'], 'String');
            }
            if (data.hasOwnProperty('computerUuid')) {
                obj['computerUuid'] = ApiClient.convertToType(data['computerUuid'], 'String');
            }
            if (data.hasOwnProperty('creationTime')) {
                obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Date');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('handled')) {
                obj['handled'] = ApiClient.convertToType(data['handled'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('moduleFirstSeenLocally')) {
                obj['moduleFirstSeenLocally'] = ApiClient.convertToType(data['moduleFirstSeenLocally'], 'Date');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
            if (data.hasOwnProperty('moduleLastExecutedLocally')) {
                obj['moduleLastExecutedLocally'] = ApiClient.convertToType(data['moduleLastExecutedLocally'], 'Date');
            }
            if (data.hasOwnProperty('moduleLgAge')) {
                obj['moduleLgAge'] = ApiClient.convertToType(data['moduleLgAge'], 'Number');
            }
            if (data.hasOwnProperty('moduleLgPopularity')) {
                obj['moduleLgPopularity'] = ApiClient.convertToType(data['moduleLgPopularity'], 'Number');
            }
            if (data.hasOwnProperty('moduleLgReputation')) {
                obj['moduleLgReputation'] = ApiClient.convertToType(data['moduleLgReputation'], 'Number');
            }
            if (data.hasOwnProperty('moduleName')) {
                obj['moduleName'] = ApiClient.convertToType(data['moduleName'], 'String');
            }
            if (data.hasOwnProperty('moduleSha1')) {
                obj['moduleSha1'] = ApiClient.convertToType(data['moduleSha1'], 'String');
            }
            if (data.hasOwnProperty('moduleSignatureType')) {
                obj['moduleSignatureType'] = ApiClient.convertToType(data['moduleSignatureType'], 'Number');
            }
            if (data.hasOwnProperty('moduleSigner')) {
                obj['moduleSigner'] = ApiClient.convertToType(data['moduleSigner'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('processCommandLine')) {
                obj['processCommandLine'] = ApiClient.convertToType(data['processCommandLine'], 'String');
            }
            if (data.hasOwnProperty('processId')) {
                obj['processId'] = ApiClient.convertToType(data['processId'], 'Number');
            }
            if (data.hasOwnProperty('processPath')) {
                obj['processPath'] = ApiClient.convertToType(data['processPath'], 'String');
            }
            if (data.hasOwnProperty('processUser')) {
                obj['processUser'] = ApiClient.convertToType(data['processUser'], 'String');
            }
            if (data.hasOwnProperty('resolved')) {
                obj['resolved'] = ApiClient.convertToType(data['resolved'], 'Boolean');
            }
            if (data.hasOwnProperty('ruleName')) {
                obj['ruleName'] = ApiClient.convertToType(data['ruleName'], 'String');
            }
            if (data.hasOwnProperty('ruleUuid')) {
                obj['ruleUuid'] = ApiClient.convertToType(data['ruleUuid'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'Number');
            }
            if (data.hasOwnProperty('severityScore')) {
                obj['severityScore'] = ApiClient.convertToType(data['severityScore'], 'Number');
            }
            if (data.hasOwnProperty('threatName')) {
                obj['threatName'] = ApiClient.convertToType(data['threatName'], 'String');
            }
            if (data.hasOwnProperty('threatUri')) {
                obj['threatUri'] = ApiClient.convertToType(data['threatUri'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} computerId
 */
DetectionDetailsResponseDETECTION.prototype['computerId'] = undefined;

/**
 * @member {String} computerName
 */
DetectionDetailsResponseDETECTION.prototype['computerName'] = undefined;

/**
 * @member {String} computerUuid
 */
DetectionDetailsResponseDETECTION.prototype['computerUuid'] = undefined;

/**
 * @member {Date} creationTime
 */
DetectionDetailsResponseDETECTION.prototype['creationTime'] = undefined;

/**
 * @member {String} event
 */
DetectionDetailsResponseDETECTION.prototype['event'] = undefined;

/**
 * @member {module:model/DetectionDetailsResponseDETECTION.HandledEnum} handled
 */
DetectionDetailsResponseDETECTION.prototype['handled'] = undefined;

/**
 * @member {Number} id
 */
DetectionDetailsResponseDETECTION.prototype['id'] = undefined;

/**
 * @member {Date} moduleFirstSeenLocally
 */
DetectionDetailsResponseDETECTION.prototype['moduleFirstSeenLocally'] = undefined;

/**
 * @member {Number} moduleId
 */
DetectionDetailsResponseDETECTION.prototype['moduleId'] = undefined;

/**
 * @member {Date} moduleLastExecutedLocally
 */
DetectionDetailsResponseDETECTION.prototype['moduleLastExecutedLocally'] = undefined;

/**
 * @member {Number} moduleLgAge
 */
DetectionDetailsResponseDETECTION.prototype['moduleLgAge'] = undefined;

/**
 * @member {Number} moduleLgPopularity
 */
DetectionDetailsResponseDETECTION.prototype['moduleLgPopularity'] = undefined;

/**
 * @member {module:model/DetectionDetailsResponseDETECTION.ModuleLgReputationEnum} moduleLgReputation
 */
DetectionDetailsResponseDETECTION.prototype['moduleLgReputation'] = undefined;

/**
 * @member {String} moduleName
 */
DetectionDetailsResponseDETECTION.prototype['moduleName'] = undefined;

/**
 * @member {String} moduleSha1
 */
DetectionDetailsResponseDETECTION.prototype['moduleSha1'] = undefined;

/**
 * @member {Number} moduleSignatureType
 */
DetectionDetailsResponseDETECTION.prototype['moduleSignatureType'] = undefined;

/**
 * @member {String} moduleSigner
 */
DetectionDetailsResponseDETECTION.prototype['moduleSigner'] = undefined;

/**
 * @member {String} note
 */
DetectionDetailsResponseDETECTION.prototype['note'] = undefined;

/**
 * @member {module:model/DetectionDetailsResponseDETECTION.PriorityEnum} priority
 */
DetectionDetailsResponseDETECTION.prototype['priority'] = undefined;

/**
 * @member {String} processCommandLine
 */
DetectionDetailsResponseDETECTION.prototype['processCommandLine'] = undefined;

/**
 * @member {Number} processId
 */
DetectionDetailsResponseDETECTION.prototype['processId'] = undefined;

/**
 * @member {String} processPath
 */
DetectionDetailsResponseDETECTION.prototype['processPath'] = undefined;

/**
 * @member {String} processUser
 */
DetectionDetailsResponseDETECTION.prototype['processUser'] = undefined;

/**
 * @member {Boolean} resolved
 */
DetectionDetailsResponseDETECTION.prototype['resolved'] = undefined;

/**
 * @member {String} ruleName
 */
DetectionDetailsResponseDETECTION.prototype['ruleName'] = undefined;

/**
 * @member {String} ruleUuid
 */
DetectionDetailsResponseDETECTION.prototype['ruleUuid'] = undefined;

/**
 * @member {Number} severity
 */
DetectionDetailsResponseDETECTION.prototype['severity'] = undefined;

/**
 * @member {Number} severityScore
 */
DetectionDetailsResponseDETECTION.prototype['severityScore'] = undefined;

/**
 * @member {String} threatName
 */
DetectionDetailsResponseDETECTION.prototype['threatName'] = undefined;

/**
 * @member {String} threatUri
 */
DetectionDetailsResponseDETECTION.prototype['threatUri'] = undefined;

/**
 * @member {module:model/DetectionDetailsResponseDETECTION.TypeEnum} type
 */
DetectionDetailsResponseDETECTION.prototype['type'] = undefined;

/**
 * @member {String} uuid
 */
DetectionDetailsResponseDETECTION.prototype['uuid'] = undefined;





/**
 * Allowed values for the <code>handled</code> property.
 * @enum {Number}
 * @readonly
 */
DetectionDetailsResponseDETECTION['HandledEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1
};


/**
 * Allowed values for the <code>moduleLgReputation</code> property.
 * @enum {Number}
 * @readonly
 */
DetectionDetailsResponseDETECTION['ModuleLgReputationEnum'] = {

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3,

    /**
     * value: 4
     * @const
     */
    "4": 4,

    /**
     * value: 5
     * @const
     */
    "5": 5,

    /**
     * value: 6
     * @const
     */
    "6": 6,

    /**
     * value: 7
     * @const
     */
    "7": 7,

    /**
     * value: 8
     * @const
     */
    "8": 8,

    /**
     * value: 9
     * @const
     */
    "9": 9
};


/**
 * Allowed values for the <code>priority</code> property.
 * @enum {Number}
 * @readonly
 */
DetectionDetailsResponseDETECTION['PriorityEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3
};


/**
 * Allowed values for the <code>type</code> property.
 * @enum {Number}
 * @readonly
 */
DetectionDetailsResponseDETECTION['TypeEnum'] = {

    /**
     * value: 0
     * @const
     */
    "0": 0,

    /**
     * value: 1
     * @const
     */
    "1": 1,

    /**
     * value: 2
     * @const
     */
    "2": 2,

    /**
     * value: 3
     * @const
     */
    "3": 3,

    /**
     * value: 4
     * @const
     */
    "4": 4,

    /**
     * value: 5
     * @const
     */
    "5": 5,

    /**
     * value: 6
     * @const
     */
    "6": 6,

    /**
     * value: 7
     * @const
     */
    "7": 7
};



export default DetectionDetailsResponseDETECTION;

