/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DetectionListResponseValue model module.
 * @module model/DetectionListResponseValue
 * @version 1.6-oas3
 */
class DetectionListResponseValue {
    /**
     * Constructs a new <code>DetectionListResponseValue</code>.
     * @alias module:model/DetectionListResponseValue
     */
    constructor() { 
        
        DetectionListResponseValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DetectionListResponseValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DetectionListResponseValue} obj Optional instance to populate.
     * @return {module:model/DetectionListResponseValue} The populated <code>DetectionListResponseValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DetectionListResponseValue();

            if (data.hasOwnProperty('computerId')) {
                obj['computerId'] = ApiClient.convertToType(data['computerId'], 'Number');
            }
            if (data.hasOwnProperty('computerName')) {
                obj['computerName'] = ApiClient.convertToType(data['computerName'], 'String');
            }
            if (data.hasOwnProperty('computerUuid')) {
                obj['computerUuid'] = ApiClient.convertToType(data['computerUuid'], 'String');
            }
            if (data.hasOwnProperty('creationTime')) {
                obj['creationTime'] = ApiClient.convertToType(data['creationTime'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('moduleId')) {
                obj['moduleId'] = ApiClient.convertToType(data['moduleId'], 'Number');
            }
            if (data.hasOwnProperty('moduleLgAge')) {
                obj['moduleLgAge'] = ApiClient.convertToType(data['moduleLgAge'], 'Number');
            }
            if (data.hasOwnProperty('moduleLgPopularity')) {
                obj['moduleLgPopularity'] = ApiClient.convertToType(data['moduleLgPopularity'], 'Number');
            }
            if (data.hasOwnProperty('moduleLgReputation')) {
                obj['moduleLgReputation'] = ApiClient.convertToType(data['moduleLgReputation'], 'Number');
            }
            if (data.hasOwnProperty('moduleName')) {
                obj['moduleName'] = ApiClient.convertToType(data['moduleName'], 'String');
            }
            if (data.hasOwnProperty('moduleSha1')) {
                obj['moduleSha1'] = ApiClient.convertToType(data['moduleSha1'], 'String');
            }
            if (data.hasOwnProperty('moduleSignatureType')) {
                obj['moduleSignatureType'] = ApiClient.convertToType(data['moduleSignatureType'], 'Number');
            }
            if (data.hasOwnProperty('moduleSigner')) {
                obj['moduleSigner'] = ApiClient.convertToType(data['moduleSigner'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('processCommandLine')) {
                obj['processCommandLine'] = ApiClient.convertToType(data['processCommandLine'], 'String');
            }
            if (data.hasOwnProperty('processId')) {
                obj['processId'] = ApiClient.convertToType(data['processId'], 'Number');
            }
            if (data.hasOwnProperty('processUser')) {
                obj['processUser'] = ApiClient.convertToType(data['processUser'], 'String');
            }
            if (data.hasOwnProperty('resolved')) {
                obj['resolved'] = ApiClient.convertToType(data['resolved'], 'Boolean');
            }
            if (data.hasOwnProperty('ruleId')) {
                obj['ruleId'] = ApiClient.convertToType(data['ruleId'], 'Number');
            }
            if (data.hasOwnProperty('ruleName')) {
                obj['ruleName'] = ApiClient.convertToType(data['ruleName'], 'String');
            }
            if (data.hasOwnProperty('ruleUuid')) {
                obj['ruleUuid'] = ApiClient.convertToType(data['ruleUuid'], 'String');
            }
            if (data.hasOwnProperty('severity')) {
                obj['severity'] = ApiClient.convertToType(data['severity'], 'Number');
            }
            if (data.hasOwnProperty('severityScore')) {
                obj['severityScore'] = ApiClient.convertToType(data['severityScore'], 'Number');
            }
            if (data.hasOwnProperty('threatName')) {
                obj['threatName'] = ApiClient.convertToType(data['threatName'], 'String');
            }
            if (data.hasOwnProperty('threatUri')) {
                obj['threatUri'] = ApiClient.convertToType(data['threatUri'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} computerId
 */
DetectionListResponseValue.prototype['computerId'] = undefined;

/**
 * @member {String} computerName
 */
DetectionListResponseValue.prototype['computerName'] = undefined;

/**
 * @member {String} computerUuid
 */
DetectionListResponseValue.prototype['computerUuid'] = undefined;

/**
 * @member {Date} creationTime
 */
DetectionListResponseValue.prototype['creationTime'] = undefined;

/**
 * @member {Number} id
 */
DetectionListResponseValue.prototype['id'] = undefined;

/**
 * @member {Number} moduleId
 */
DetectionListResponseValue.prototype['moduleId'] = undefined;

/**
 * @member {Number} moduleLgAge
 */
DetectionListResponseValue.prototype['moduleLgAge'] = undefined;

/**
 * @member {Number} moduleLgPopularity
 */
DetectionListResponseValue.prototype['moduleLgPopularity'] = undefined;

/**
 * @member {Number} moduleLgReputation
 */
DetectionListResponseValue.prototype['moduleLgReputation'] = undefined;

/**
 * @member {String} moduleName
 */
DetectionListResponseValue.prototype['moduleName'] = undefined;

/**
 * @member {String} moduleSha1
 */
DetectionListResponseValue.prototype['moduleSha1'] = undefined;

/**
 * @member {module:model/DetectionListResponseValue.ModuleSignatureTypeEnum} moduleSignatureType
 */
DetectionListResponseValue.prototype['moduleSignatureType'] = undefined;

/**
 * @member {String} moduleSigner
 */
DetectionListResponseValue.prototype['moduleSigner'] = undefined;

/**
 * @member {String} note
 */
DetectionListResponseValue.prototype['note'] = undefined;

/**
 * @member {Number} priority
 */
DetectionListResponseValue.prototype['priority'] = undefined;

/**
 * @member {String} processCommandLine
 */
DetectionListResponseValue.prototype['processCommandLine'] = undefined;

/**
 * @member {Number} processId
 */
DetectionListResponseValue.prototype['processId'] = undefined;

/**
 * @member {String} processUser
 */
DetectionListResponseValue.prototype['processUser'] = undefined;

/**
 * @member {Boolean} resolved
 */
DetectionListResponseValue.prototype['resolved'] = undefined;

/**
 * @member {Number} ruleId
 */
DetectionListResponseValue.prototype['ruleId'] = undefined;

/**
 * @member {String} ruleName
 */
DetectionListResponseValue.prototype['ruleName'] = undefined;

/**
 * @member {String} ruleUuid
 */
DetectionListResponseValue.prototype['ruleUuid'] = undefined;

/**
 * @member {Number} severity
 */
DetectionListResponseValue.prototype['severity'] = undefined;

/**
 * @member {Number} severityScore
 */
DetectionListResponseValue.prototype['severityScore'] = undefined;

/**
 * @member {String} threatName
 */
DetectionListResponseValue.prototype['threatName'] = undefined;

/**
 * @member {String} threatUri
 */
DetectionListResponseValue.prototype['threatUri'] = undefined;

/**
 * @member {Number} type
 */
DetectionListResponseValue.prototype['type'] = undefined;

/**
 * @member {String} uuid
 */
DetectionListResponseValue.prototype['uuid'] = undefined;





/**
 * Allowed values for the <code>moduleSignatureType</code> property.
 * @enum {Number}
 * @readonly
 */
DetectionListResponseValue['ModuleSignatureTypeEnum'] = {

    /**
     * value: 60
     * @const
     */
    "60": 60,

    /**
     * value: 70
     * @const
     */
    "70": 70,

    /**
     * value: 75
     * @const
     */
    "75": 75,

    /**
     * value: 80
     * @const
     */
    "80": 80,

    /**
     * value: 90
     * @const
     */
    "90": 90
};



export default DetectionListResponseValue;

