/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExclusionDetailsResponseEXCLUSION from './ExclusionDetailsResponseEXCLUSION';

/**
 * The ExclusionDetailsResponse model module.
 * @module model/ExclusionDetailsResponse
 * @version 1.6-oas3
 */
class ExclusionDetailsResponse {
    /**
     * Constructs a new <code>ExclusionDetailsResponse</code>.
     * @alias module:model/ExclusionDetailsResponse
     */
    constructor() { 
        
        ExclusionDetailsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExclusionDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExclusionDetailsResponse} obj Optional instance to populate.
     * @return {module:model/ExclusionDetailsResponse} The populated <code>ExclusionDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExclusionDetailsResponse();

            if (data.hasOwnProperty('EXCLUSION')) {
                obj['EXCLUSION'] = ExclusionDetailsResponseEXCLUSION.constructFromObject(data['EXCLUSION']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ExclusionDetailsResponseEXCLUSION} EXCLUSION
 */
ExclusionDetailsResponse.prototype['EXCLUSION'] = undefined;






export default ExclusionDetailsResponse;

