/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExclusionCreateRequest model module.
 * @module model/ExclusionCreateRequest
 * @version 1.6-oas3
 */
class ExclusionCreateRequest {
    /**
     * Constructs a new <code>ExclusionCreateRequest</code>.
     * @alias module:model/ExclusionCreateRequest
     * @param body {String} 
     * @param autoResolve {Boolean} 
     * @param name {String} 
     */
    constructor(body, autoResolve, name) { 
        
        ExclusionCreateRequest.initialize(this, body, autoResolve, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, body, autoResolve, name) { 
        obj['body'] = body;
        obj['autoResolve'] = autoResolve;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ExclusionCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExclusionCreateRequest} obj Optional instance to populate.
     * @return {module:model/ExclusionCreateRequest} The populated <code>ExclusionCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExclusionCreateRequest();

            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('autoResolve')) {
                obj['autoResolve'] = ApiClient.convertToType(data['autoResolve'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ruleIds')) {
                obj['ruleIds'] = ApiClient.convertToType(data['ruleIds'], ['Number']);
            }
            if (data.hasOwnProperty('ruleUuids')) {
                obj['ruleUuids'] = ApiClient.convertToType(data['ruleUuids'], ['String']);
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} body
 */
ExclusionCreateRequest.prototype['body'] = undefined;

/**
 * @member {Boolean} autoResolve
 */
ExclusionCreateRequest.prototype['autoResolve'] = undefined;

/**
 * @member {String} name
 */
ExclusionCreateRequest.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} ruleIds
 */
ExclusionCreateRequest.prototype['ruleIds'] = undefined;

/**
 * @member {Array.<String>} ruleUuids
 */
ExclusionCreateRequest.prototype['ruleUuids'] = undefined;

/**
 * @member {String} note
 */
ExclusionCreateRequest.prototype['note'] = undefined;






export default ExclusionCreateRequest;

