/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExclusionDetailsResponseEXCLUSION model module.
 * @module model/ExclusionDetailsResponseEXCLUSION
 * @version 1.6-oas3
 */
class ExclusionDetailsResponseEXCLUSION {
    /**
     * Constructs a new <code>ExclusionDetailsResponseEXCLUSION</code>.
     * @alias module:model/ExclusionDetailsResponseEXCLUSION
     */
    constructor() { 
        
        ExclusionDetailsResponseEXCLUSION.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExclusionDetailsResponseEXCLUSION</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExclusionDetailsResponseEXCLUSION} obj Optional instance to populate.
     * @return {module:model/ExclusionDetailsResponseEXCLUSION} The populated <code>ExclusionDetailsResponseEXCLUSION</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExclusionDetailsResponseEXCLUSION();

            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('ruleIds')) {
                obj['ruleIds'] = ApiClient.convertToType(data['ruleIds'], ['Number']);
            }
            if (data.hasOwnProperty('ruleUuids')) {
                obj['ruleUuids'] = ApiClient.convertToType(data['ruleUuids'], ['String']);
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} body
 */
ExclusionDetailsResponseEXCLUSION.prototype['body'] = undefined;

/**
 * @member {Boolean} enabled
 */
ExclusionDetailsResponseEXCLUSION.prototype['enabled'] = undefined;

/**
 * @member {Number} id
 */
ExclusionDetailsResponseEXCLUSION.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ExclusionDetailsResponseEXCLUSION.prototype['name'] = undefined;

/**
 * @member {String} note
 */
ExclusionDetailsResponseEXCLUSION.prototype['note'] = undefined;

/**
 * @member {Array.<Number>} ruleIds
 */
ExclusionDetailsResponseEXCLUSION.prototype['ruleIds'] = undefined;

/**
 * @member {Array.<String>} ruleUuids
 */
ExclusionDetailsResponseEXCLUSION.prototype['ruleUuids'] = undefined;

/**
 * @member {String} uuid
 */
ExclusionDetailsResponseEXCLUSION.prototype['uuid'] = undefined;






export default ExclusionDetailsResponseEXCLUSION;

