/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExclusionListResponseValue model module.
 * @module model/ExclusionListResponseValue
 * @version 1.6-oas3
 */
class ExclusionListResponseValue {
    /**
     * Constructs a new <code>ExclusionListResponseValue</code>.
     * @alias module:model/ExclusionListResponseValue
     */
    constructor() { 
        
        ExclusionListResponseValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExclusionListResponseValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExclusionListResponseValue} obj Optional instance to populate.
     * @return {module:model/ExclusionListResponseValue} The populated <code>ExclusionListResponseValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExclusionListResponseValue();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} enabled
 */
ExclusionListResponseValue.prototype['enabled'] = undefined;

/**
 * @member {Number} id
 */
ExclusionListResponseValue.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ExclusionListResponseValue.prototype['name'] = undefined;

/**
 * @member {String} note
 */
ExclusionListResponseValue.prototype['note'] = undefined;

/**
 * @member {String} uuid
 */
ExclusionListResponseValue.prototype['uuid'] = undefined;






export default ExclusionListResponseValue;

