/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExecutableUnblockRequest model module.
 * @module model/ExecutableUnblockRequest
 * @version 1.6-oas3
 */
class ExecutableUnblockRequest {
    /**
     * Constructs a new <code>ExecutableUnblockRequest</code>.
     * @alias module:model/ExecutableUnblockRequest
     */
    constructor() { 
        
        ExecutableUnblockRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExecutableUnblockRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExecutableUnblockRequest} obj Optional instance to populate.
     * @return {module:model/ExecutableUnblockRequest} The populated <code>ExecutableUnblockRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExecutableUnblockRequest();

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} note
 */
ExecutableUnblockRequest.prototype['note'] = undefined;






export default ExecutableUnblockRequest;

