/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleCreateRequestActionsAction model module.
 * @module model/RuleCreateRequestActionsAction
 * @version 1.6-oas3
 */
class RuleCreateRequestActionsAction {
    /**
     * Constructs a new <code>RuleCreateRequestActionsAction</code>.
     * @alias module:model/RuleCreateRequestActionsAction
     */
    constructor() { 
        
        RuleCreateRequestActionsAction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestActionsAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestActionsAction} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestActionsAction} The populated <code>RuleCreateRequestActionsAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestActionsAction();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RuleCreateRequestActionsAction.NameEnum} name
 */
RuleCreateRequestActionsAction.prototype['name'] = undefined;





/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
RuleCreateRequestActionsAction['NameEnum'] = {

    /**
     * value: "TriggerDetection"
     * @const
     */
    "TriggerDetection": "TriggerDetection",

    /**
     * value: "MarkAsScript"
     * @const
     */
    "MarkAsScript": "MarkAsScript",

    /**
     * value: "MarkAsCompromised"
     * @const
     */
    "MarkAsCompromised": "MarkAsCompromised",

    /**
     * value: "HideCommandLine"
     * @const
     */
    "HideCommandLine": "HideCommandLine",

    /**
     * value: "BlockProcessExecutable"
     * @const
     */
    "BlockProcessExecutable": "BlockProcessExecutable",

    /**
     * value: "CleanAndBlockProcessExecutable"
     * @const
     */
    "CleanAndBlockProcessExecutable": "CleanAndBlockProcessExecutable",

    /**
     * value: "BlockParentProcessExecutable"
     * @const
     */
    "BlockParentProcessExecutable": "BlockParentProcessExecutable",

    /**
     * value: "CleanAndBlockParentProcessExecutable"
     * @const
     */
    "CleanAndBlockParentProcessExecutable": "CleanAndBlockParentProcessExecutable",

    /**
     * value: "IsolateFromNetwork"
     * @const
     */
    "IsolateFromNetwork": "IsolateFromNetwork",

    /**
     * value: "DropEvent"
     * @const
     */
    "DropEvent": "DropEvent"
};



export default RuleCreateRequestActionsAction;

