/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleCreateRequestDescription model module.
 * @module model/RuleCreateRequestDescription
 * @version 1.6-oas3
 */
class RuleCreateRequestDescription {
    /**
     * Constructs a new <code>RuleCreateRequestDescription</code>.
     * @alias module:model/RuleCreateRequestDescription
     */
    constructor() { 
        
        RuleCreateRequestDescription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestDescription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestDescription} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestDescription} The populated <code>RuleCreateRequestDescription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestDescription();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('explanation')) {
                obj['explanation'] = ApiClient.convertToType(data['explanation'], 'String');
            }
            if (data.hasOwnProperty('os')) {
                obj['os'] = ApiClient.convertToType(data['os'], 'String');
            }
            if (data.hasOwnProperty('mitreattackid')) {
                obj['mitreattackid'] = ApiClient.convertToType(data['mitreattackid'], 'String');
            }
            if (data.hasOwnProperty('maliciousCauses')) {
                obj['maliciousCauses'] = ApiClient.convertToType(data['maliciousCauses'], 'String');
            }
            if (data.hasOwnProperty('benignCauses')) {
                obj['benignCauses'] = ApiClient.convertToType(data['benignCauses'], 'String');
            }
            if (data.hasOwnProperty('recommendedActions')) {
                obj['recommendedActions'] = ApiClient.convertToType(data['recommendedActions'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
RuleCreateRequestDescription.prototype['name'] = undefined;

/**
 * @member {String} category
 */
RuleCreateRequestDescription.prototype['category'] = undefined;

/**
 * @member {String} explanation
 */
RuleCreateRequestDescription.prototype['explanation'] = undefined;

/**
 * @member {module:model/RuleCreateRequestDescription.OsEnum} os
 */
RuleCreateRequestDescription.prototype['os'] = undefined;

/**
 * @member {String} mitreattackid
 */
RuleCreateRequestDescription.prototype['mitreattackid'] = undefined;

/**
 * @member {String} maliciousCauses
 */
RuleCreateRequestDescription.prototype['maliciousCauses'] = undefined;

/**
 * @member {String} benignCauses
 */
RuleCreateRequestDescription.prototype['benignCauses'] = undefined;

/**
 * @member {String} recommendedActions
 */
RuleCreateRequestDescription.prototype['recommendedActions'] = undefined;





/**
 * Allowed values for the <code>os</code> property.
 * @enum {String}
 * @readonly
 */
RuleCreateRequestDescription['OsEnum'] = {

    /**
     * value: "Windows"
     * @const
     */
    "Windows": "Windows",

    /**
     * value: "OSX"
     * @const
     */
    "OSX": "OSX",

    /**
     * value: "ANY"
     * @const
     */
    "ANY": "ANY"
};



export default RuleCreateRequestDescription;

