/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RuleDetailsResponseRULE from './RuleDetailsResponseRULE';

/**
 * The RuleDetailsResponse model module.
 * @module model/RuleDetailsResponse
 * @version 1.6-oas3
 */
class RuleDetailsResponse {
    /**
     * Constructs a new <code>RuleDetailsResponse</code>.
     * @alias module:model/RuleDetailsResponse
     */
    constructor() { 
        
        RuleDetailsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleDetailsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleDetailsResponse} obj Optional instance to populate.
     * @return {module:model/RuleDetailsResponse} The populated <code>RuleDetailsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleDetailsResponse();

            if (data.hasOwnProperty('RULE')) {
                obj['RULE'] = RuleDetailsResponseRULE.constructFromObject(data['RULE']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RuleDetailsResponseRULE} RULE
 */
RuleDetailsResponse.prototype['RULE'] = undefined;






export default RuleDetailsResponse;

