/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RuleCreateRequestActionsAction from './RuleCreateRequestActionsAction';

/**
 * The RuleCreateRequestActions model module.
 * @module model/RuleCreateRequestActions
 * @version 1.6-oas3
 */
class RuleCreateRequestActions {
    /**
     * Constructs a new <code>RuleCreateRequestActions</code>.
     * @alias module:model/RuleCreateRequestActions
     */
    constructor() { 
        
        RuleCreateRequestActions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestActions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestActions} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestActions} The populated <code>RuleCreateRequestActions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestActions();

            if (data.hasOwnProperty('action')) {
                obj['action'] = RuleCreateRequestActionsAction.constructFromObject(data['action']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RuleCreateRequestActionsAction} action
 */
RuleCreateRequestActions.prototype['action'] = undefined;






export default RuleCreateRequestActions;

