/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleCreateRequestDefinitionAncestor model module.
 * @module model/RuleCreateRequestDefinitionAncestor
 * @version 1.6-oas3
 */
class RuleCreateRequestDefinitionAncestor {
    /**
     * Constructs a new <code>RuleCreateRequestDefinitionAncestor</code>.
     * @alias module:model/RuleCreateRequestDefinitionAncestor
     */
    constructor() { 
        
        RuleCreateRequestDefinitionAncestor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestDefinitionAncestor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestDefinitionAncestor} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestDefinitionAncestor} The populated <code>RuleCreateRequestDefinitionAncestor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestDefinitionAncestor();

            if (data.hasOwnProperty('distance')) {
                obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
            }
            if (data.hasOwnProperty('unique')) {
                obj['unique'] = ApiClient.convertToType(data['unique'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} distance
 */
RuleCreateRequestDefinitionAncestor.prototype['distance'] = undefined;

/**
 * @member {Boolean} unique
 */
RuleCreateRequestDefinitionAncestor.prototype['unique'] = undefined;






export default RuleCreateRequestDefinitionAncestor;

