/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RuleCreateRequestDefinitionAncestor from './RuleCreateRequestDefinitionAncestor';
import RuleCreateRequestDefinitionOperations from './RuleCreateRequestDefinitionOperations';

/**
 * The RuleCreateRequestDefinition model module.
 * @module model/RuleCreateRequestDefinition
 * @version 1.6-oas3
 */
class RuleCreateRequestDefinition {
    /**
     * Constructs a new <code>RuleCreateRequestDefinition</code>.
     * @alias module:model/RuleCreateRequestDefinition
     */
    constructor() { 
        
        RuleCreateRequestDefinition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestDefinition} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestDefinition} The populated <code>RuleCreateRequestDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestDefinition();

            if (data.hasOwnProperty('ancestor')) {
                obj['ancestor'] = RuleCreateRequestDefinitionAncestor.constructFromObject(data['ancestor']);
            }
            if (data.hasOwnProperty('parentprocess')) {
                obj['parentprocess'] = ApiClient.convertToType(data['parentprocess'], Object);
            }
            if (data.hasOwnProperty('process')) {
                obj['process'] = ApiClient.convertToType(data['process'], Object);
            }
            if (data.hasOwnProperty('operations')) {
                obj['operations'] = RuleCreateRequestDefinitionOperations.constructFromObject(data['operations']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RuleCreateRequestDefinitionAncestor} ancestor
 */
RuleCreateRequestDefinition.prototype['ancestor'] = undefined;

/**
 * @member {Object} parentprocess
 */
RuleCreateRequestDefinition.prototype['parentprocess'] = undefined;

/**
 * @member {Object} process
 */
RuleCreateRequestDefinition.prototype['process'] = undefined;

/**
 * @member {module:model/RuleCreateRequestDefinitionOperations} operations
 */
RuleCreateRequestDefinition.prototype['operations'] = undefined;






export default RuleCreateRequestDefinition;

