/**
 * ESET Enterprise Inspector
 * ESET Enterprise Inspector REST API definition
 *
 * The version of the OpenAPI document: 1.6-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RuleCreateRequestDefinitionOperationsOperation model module.
 * @module model/RuleCreateRequestDefinitionOperationsOperation
 * @version 1.6-oas3
 */
class RuleCreateRequestDefinitionOperationsOperation {
    /**
     * Constructs a new <code>RuleCreateRequestDefinitionOperationsOperation</code>.
     * @alias module:model/RuleCreateRequestDefinitionOperationsOperation
     */
    constructor() { 
        
        RuleCreateRequestDefinitionOperationsOperation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RuleCreateRequestDefinitionOperationsOperation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RuleCreateRequestDefinitionOperationsOperation} obj Optional instance to populate.
     * @return {module:model/RuleCreateRequestDefinitionOperationsOperation} The populated <code>RuleCreateRequestDefinitionOperationsOperation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RuleCreateRequestDefinitionOperationsOperation();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} type
 */
RuleCreateRequestDefinitionOperationsOperation.prototype['type'] = undefined;






export default RuleCreateRequestDefinitionOperationsOperation;

