"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rule_details_response_rule import RuleDetailsResponseRULE
globals()['RuleDetailsResponseRULE'] = RuleDetailsResponseRULE
from openapi_client.model.rule_details_response import RuleDetailsResponse


class TestRuleDetailsResponse(unittest.TestCase):
    """RuleDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleDetailsResponse(self):
        """Test RuleDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuleDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
