"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.rules_api import RulesApi  # noqa: E501


class TestRulesApi(unittest.TestCase):
    """RulesApi unit test stubs"""

    def setUp(self):
        self.api = RulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_rule(self):
        """Test case for create_rule

        Creates a new rule  # noqa: E501
        """
        pass

    def test_delete_rule(self):
        """Test case for delete_rule

        Deletes a rule  # noqa: E501
        """
        pass

    def test_edit_rule(self):
        """Test case for edit_rule

        Edits rule body  # noqa: E501
        """
        pass

    def test_get_rule_details(self):
        """Test case for get_rule_details

        Gets a single rule  # noqa: E501
        """
        pass

    def test_list_rules(self):
        """Test case for list_rules

        List rules  # noqa: E501
        """
        pass

    def test_update_rule(self):
        """Test case for update_rule

        Updates particular rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
