"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.integrate_response import IntegrateResponse


class TestIntegrateResponse(unittest.TestCase):
    """IntegrateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrateResponse(self):
        """Test IntegrateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IntegrateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
