"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.isolate_response import IsolateResponse


class TestIsolateResponse(unittest.TestCase):
    """IsolateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIsolateResponse(self):
        """Test IsolateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IsolateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
