"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rule_create_request_definition_operations_operation import RuleCreateRequestDefinitionOperationsOperation
globals()['RuleCreateRequestDefinitionOperationsOperation'] = RuleCreateRequestDefinitionOperationsOperation
from openapi_client.model.rule_create_request_definition_operations import RuleCreateRequestDefinitionOperations


class TestRuleCreateRequestDefinitionOperations(unittest.TestCase):
    """RuleCreateRequestDefinitionOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleCreateRequestDefinitionOperations(self):
        """Test RuleCreateRequestDefinitionOperations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuleCreateRequestDefinitionOperations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
