"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.remediation_api import RemediationApi  # noqa: E501


class TestRemediationApi(unittest.TestCase):
    """RemediationApi unit test stubs"""

    def setUp(self):
        self.api = RemediationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_block_executable(self):
        """Test case for block_executable

        Block an executable  # noqa: E501
        """
        pass

    def test_unblock_executable(self):
        """Test case for unblock_executable

        Unblock an executable  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
