"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.exclusions_api import ExclusionsApi  # noqa: E501


class TestExclusionsApi(unittest.TestCase):
    """ExclusionsApi unit test stubs"""

    def setUp(self):
        self.api = ExclusionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_exclusion(self):
        """Test case for create_exclusion

        Creates a new exclusion  # noqa: E501
        """
        pass

    def test_delete_exclusion(self):
        """Test case for delete_exclusion

        Deletes an exclusion  # noqa: E501
        """
        pass

    def test_edit_exclusion(self):
        """Test case for edit_exclusion

        Edits exclusion body  # noqa: E501
        """
        pass

    def test_get_exclusion_details(self):
        """Test case for get_exclusion_details

        Gets a single exclusion  # noqa: E501
        """
        pass

    def test_get_exclusions_by_rule(self):
        """Test case for get_exclusions_by_rule

        Get exclusions associated with a rule  # noqa: E501
        """
        pass

    def test_list_exclusions(self):
        """Test case for list_exclusions

        List exclusions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
