"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.detection_list_response_value import DetectionListResponseValue
globals()['DetectionListResponseValue'] = DetectionListResponseValue
from openapi_client.model.detection_list_response import DetectionListResponse


class TestDetectionListResponse(unittest.TestCase):
    """DetectionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetectionListResponse(self):
        """Test DetectionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetectionListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
