"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.computers_api import ComputersApi  # noqa: E501


class TestComputersApi(unittest.TestCase):
    """ComputersApi unit test stubs"""

    def setUp(self):
        self.api = ComputersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_integrate_computer(self):
        """Test case for integrate_computer

        Integrate a computer back into the network  # noqa: E501
        """
        pass

    def test_isolate_computer(self):
        """Test case for isolate_computer

        Isolate a computer from the network  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
