"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.rule_list_response_value import RuleListResponseValue


class TestRuleListResponseValue(unittest.TestCase):
    """RuleListResponseValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleListResponseValue(self):
        """Test RuleListResponseValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RuleListResponseValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
