"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_post(self):
        """Test case for authenticate_post

        Authentication  # noqa: E501
        """
        pass

    def test_authenticate_put(self):
        """Test case for authenticate_put

        Authentication  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
