"""
    ESET Enterprise Inspector

    ESET Enterprise Inspector REST API definition  # noqa: E501

    The version of the OpenAPI document: 1.6-oas3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.detection_details_response_detection import DetectionDetailsResponseDETECTION
globals()['DetectionDetailsResponseDETECTION'] = DetectionDetailsResponseDETECTION
from openapi_client.model.detection_details_response import DetectionDetailsResponse


class TestDetectionDetailsResponse(unittest.TestCase):
    """DetectionDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDetectionDetailsResponse(self):
        """Test DetectionDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DetectionDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
